# Min builder-stage
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run lint || echo "No lint script found, skipping."
RUN npm test || echo "No tests found, skipping."
RUN npm run build


# Min runtime-stage
FROM nginx:stable-alpine AS runtime


COPY --from=builder /app/dist /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
