version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: my-backend:latest
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
