# min builder-stage
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm test || echo "No tests found, skipping..."

# min runtime-stage
FROM node:18-alpine AS runtime
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app .
EXPOSE 5000
CMD ["npm", "start"]
