name: Backend CI

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules (Backend)
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests found, skipping."

      - name: Build backend
        run: npm run build || echo "No build script, skipping."

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: server/dist/ # eller vad din build output är
