name: CI Pipeline - Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    name: Build & Deploy Frontend (Develop)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # package.json ligger här
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Node 22 löser EBADENGINE varningarna

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint || echo "No lint script, skipping."

      - name: Run frontend tests
        run: npm test || echo "No tests found, skipping."

      - name: Build frontend
        run: npm run build

      - name: Deploy to Azure SWA (Staging)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"      
          output_location: "dist"  
