name: CI Pipeline - Main (prod-test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ------------------------
  # Backend: Build & Deploy
  # ------------------------
  backend:
    name: Build & Deploy Backend (prod-test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Lint backend
        run: npm run lint || echo "No lint script, skipping."

      - name: Run tests
        run: npm test || echo "No tests found, skipping."

      - name: Build backend
        run: npm run build || echo "No build script, skipping."

      # ------------------------
      # Docker Build & Push
      # ------------------------
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: traningrobin.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t traningrobin.azurecr.io/server:dev .

      - name: Push Docker image
        run: docker push traningrobin.azurecr.io/server:dev

      # ------------------------
      # Deploy to Azure Container App (prod-test)
      # ------------------------
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        run: |
          az containerapp update \
            --name server-api-prod \
            --resource-group rg-training-Rob \
            --image traningrobin.azurecr.io/server:dev

  # ------------------------
  # Frontend: Build & Deploy
  # ------------------------
  frontend:
    name: Build & Deploy Frontend (prod-test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint || echo "No lint script, skipping."

      - name: Run frontend tests
        run: npm test || echo "No tests found, skipping."

      - name: Build frontend
        run: npm run build

      - name: Deploy to Azure SWA (prod-test)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          app_artifact_location: "frontend/dist"
          skip_app_build: true
