name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {} 

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: server/dist/

      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/


      - name: Deploy to server
        run: |
          echo "Deploying backend and frontend..."
          # scp/rsync till server eller docker push osv.
