name: Docker Build & Push Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./server

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

      - name: Run docker-compose locally
        run: docker compose up -d --build
