name: Docker Build Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./server

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

      - name: Run docker-compose
        run: docker compose -f docker-compose.yml up --build -d
