name: Prod Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm run build || echo "No build script, skipping."

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: traningrobin.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t traningrobin.azurecr.io/server:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker push traningrobin.azurecr.io/server:$IMAGE_TAG

      - name: Deploy to Azure Container App (PROD)
        uses: azure/CLI@v1
        with:
          azcliversion: '2.69.0'
          inlineScript: |
            IMAGE_TAG=$(git rev-parse --short HEAD)
            az containerapp update \
              --name server-api-prod \
              --resource-group rg-training-Rob \
              --image traningrobin.azurecr.io/server:$IMAGE_TAG
