name: Prod Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install


      - name: Install dependencies
        run: npm install


      - name: Lint
        run: npm run lint || echo "No lint script, skipping."


      - name: Run tests
        run: npm test || echo "No tests found, skipping."


      - name: Build backend
        run: npm run build || echo "No build script, skipping."

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: traningrobin.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build Docker image
        run: docker build -t traningrobin.azurecr.io/server:${GITHUB_SHA::8} .


      - name: Push Docker image
        run: docker push traningrobin.azurecr.io/server:${GITHUB_SHA::8}


      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to Azure Container App (DEV)
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "Deploying image tag $IMAGE_TAG"
          az containerapp update \
            --name server-api-dev \
            --resource-group rg-training-Rob \
            --subscription 9f7950b2-adaf-460b-b955-a970df175c32 \
            --image traningrobin.azurecr.io/server:$IMAGE_TAG
        shell: bash
