name: Prod CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build Backend, Generate Swagger & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint || echo "No lint script, skipping."

      - name: Run tests
        run: npm test || echo "No tests found, skipping."

      - name: Build backend
        run: npm run build || echo "No build script, skipping."

      - name: Generate Swagger Docs
        run: npm run generate-docs

      - name: Copy Swagger to frontend
        run: cp ./docs/swagger.json ../frontend/public/swagger.json

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: traningrobin.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Backend Docker image
        run: docker build -t traningrobin.azurecr.io/server:${GITHUB_SHA::8} .

      - name: Push Backend Docker image
        run: docker push traningrobin.azurecr.io/server:${GITHUB_SHA::8}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure Container App
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          az containerapp update \
            --name server-api-prod \
            --resource-group rg-training-Rob \
            --image traningrobin.azurecr.io/server:$IMAGE_TAG
        shell: bash

  frontend:
    name: Build Frontend & Deploy to Azure SWA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint || echo "No lint script, skipping."

      - name: Run tests
        run: npm test || echo "No tests found, skipping."

      - name: Build frontend
        run: npm run build

      - name: Deploy Frontend to Azure SWA
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          app_artifact_location: "dist"
          skip_app_build: true
